spring:
  thymeleaf:
    mode: HTML5
    cache: false

  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/communitys;AUTO_SERVER=TRUE
    username: root
    password: 123456


github:
  client_id:  428df01afde56004fcc1
  client_secret: 9c7ecc7603af3db402aa92b7c2f12e752a9930ce
  redirect_uri: http://localhost:8080/callback

